import { describe, it, expect } from "vitest";
import { translate } from "../src/translate.ts";
import { readFileSync } from "node:fs";

describe("translate — core behavior", () => {
  it("translates a simple CREATE TABLE", () => {
    const { oracle } = translate(`CREATE TABLE t (id serial, name text);`);
    expect(oracle).toContain("NUMBER(10) GENERATED BY DEFAULT AS IDENTITY");
    expect(oracle).toContain("CLOB");
  });

  it("preserves COMMENT ON statements verbatim", () => {
    const sql = `CREATE TABLE users(id serial);\nCOMMENT ON TABLE users IS 'User account data';\n`;
    const { oracle } = translate(sql);
    expect(oracle).toContain("COMMENT ON TABLE users IS 'User account data'");
  });

  it("translates boolean DEFAULT true → DEFAULT 1", () => {
    const { oracle } = translate(`CREATE TABLE t (active boolean DEFAULT true);`);
    expect(oracle).toMatch(/DEFAULT\s+1/);
    expect(oracle).not.toMatch(/DEFAULT\s+true/i);
  });

  it("strips IF NOT EXISTS from CREATE TABLE and warns", () => {
    const { oracle, report } = translate(`CREATE TABLE IF NOT EXISTS t (id serial);`);
    expect(oracle).not.toMatch(/IF\s+NOT\s+EXISTS/i);
    expect(oracle).toMatch(/CREATE\s+TABLE\s+t\s*\(/);
    const md = report.toMarkdown("test.sql");
    expect(md).toMatch(/IF NOT EXISTS/);
  });

  it("translates DEFAULT now() → DEFAULT SYSTIMESTAMP", () => {
    const { oracle } = translate(`CREATE TABLE t (created_at timestamp DEFAULT now());`);
    expect(oracle).toContain("DEFAULT SYSTIMESTAMP");
  });

  it("warns and drops gen_random_uuid() default", () => {
    const { oracle, report } = translate(
      `CREATE TABLE t (id uuid DEFAULT gen_random_uuid());`,
    );
    expect(oracle).not.toMatch(/gen_random_uuid/);
    const md = report.toMarkdown("test");
    expect(md).toMatch(/gen_random_uuid|UUID/i);
    expect(md).toMatch(/SYS_GUID|trigger/i);
  });

  it("warns on schema-qualified table names but does not rewrite", () => {
    const { oracle, report } = translate(`CREATE TABLE public.users (id serial);`);
    expect(oracle).toContain("public.users"); // unchanged
    const md = report.toMarkdown("test");
    expect(md).toMatch(/schema/i);
  });

  it("warns on identifiers > 30 chars but does not rewrite", () => {
    const longName = "a".repeat(35);
    const { oracle, report } = translate(`CREATE TABLE ${longName} (id serial);`);
    expect(oracle).toContain(longName); // unchanged
    expect(report.hasHigh()).toBe(true);
    expect(report.toMarkdown("t")).toMatch(/long identifier/i);
  });

  it("normalizes CRLF input to produce identical output", () => {
    const lf = `CREATE TABLE t (id serial);\nCREATE TABLE u (id text);\n`;
    const crlf = lf.replace(/\n/g, "\r\n");
    const a = translate(lf).oracle.replace(/\s+/g, " ").trim();
    const b = translate(crlf.replace(/\r\n/g, "\n")).oracle.replace(/\s+/g, " ").trim();
    expect(a).toBe(b);
  });

  it("preserves PL/pgSQL bodies verbatim and warns", () => {
    const sql = `CREATE FUNCTION f() RETURNS void AS $$ BEGIN NULL; END; $$ LANGUAGE plpgsql;`;
    const { oracle, report } = translate(sql);
    expect(oracle).toContain("plpgsql");
    expect(report.hasHigh()).toBe(true);
  });

  it("drops USING gin/gist on indexes with high warning", () => {
    const { oracle, report } = translate(
      `CREATE INDEX idx_data ON t USING gin (data);`,
    );
    expect(oracle).not.toMatch(/USING\s+gin/i);
    expect(report.hasHigh()).toBe(true);
  });

  it("translates Ghost schema end-to-end without throwing", () => {
    const sql = readFileSync("examples/ghost/postgres.sql", "utf8");
    const { oracle, report } = translate(sql, "ghost");
    expect(oracle.length).toBeGreaterThan(1000);
    expect(oracle).toContain("VARCHAR2");
    expect(oracle).toContain("CLOB");
    expect(oracle).toContain("RAW(16)"); // posts.uuid
    // Ghost uses varchar(24) IDs (object IDs), not serial — no IDENTITY expected.
    // Should produce warnings: jsonb (sessions.session_data), uuid default (posts.uuid)
    expect(report.count()).toBeGreaterThan(0);
  });

  it("translates a CREATE TABLE that begins with a leading comment", () => {
    // Regression: dispatcher used to classify on the raw trimmed text and
    // skipped statements whose first non-whitespace chars were `--`.
    const sql = `-- users table\nCREATE TABLE users (id serial, email text);`;
    const { oracle } = translate(sql);
    expect(oracle).toContain("-- users table");
    expect(oracle).toContain("NUMBER(10) GENERATED BY DEFAULT AS IDENTITY");
    expect(oracle).toContain("CLOB");
  });

  it("translates a CREATE TABLE that begins with a /* block comment */", () => {
    const sql = `/* header\n   multi-line */\nCREATE TABLE t (id serial);`;
    const { oracle } = translate(sql);
    expect(oracle).toContain("/* header");
    expect(oracle).toContain("NUMBER(10) GENERATED BY DEFAULT AS IDENTITY");
  });
});
