

CREATE TABLE tenants (
  id RAW(16) PRIMARY KEY,
  slug VARCHAR2(64) NOT NULL UNIQUE,
  name VARCHAR2(200) NOT NULL,
  plan VARCHAR2(32) NOT NULL DEFAULT 'starter',
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT SYSTIMESTAMP,
  settings CLOB CHECK (SETTINGS IS JSON) NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE users (
  id RAW(16) PRIMARY KEY,
  tenant_id RAW(16) NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  email VARCHAR2(254) NOT NULL,
  password_hash VARCHAR2(255) NOT NULL,
  full_name VARCHAR2(200),
  is_active NUMBER(1) NOT NULL DEFAULT 1,
  last_login_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT SYSTIMESTAMP,
  UNIQUE (tenant_id, email)
);

CREATE TABLE workspaces (
  id RAW(16) PRIMARY KEY,
  tenant_id RAW(16) NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  name VARCHAR2(200) NOT NULL,
  metadata CLOB CHECK (METADATA IS JSON) NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT SYSTIMESTAMP
);

CREATE TABLE projects (
  id RAW(16) PRIMARY KEY,
  tenant_id RAW(16) NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  workspace_id RAW(16) NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  name VARCHAR2(200) NOT NULL,
  description CLOB,
  status VARCHAR2(32) NOT NULL DEFAULT 'active',
  config CLOB CHECK (CONFIG IS JSON) NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT SYSTIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT SYSTIMESTAMP
);

CREATE TABLE api_keys (
  id RAW(16) PRIMARY KEY,
  tenant_id RAW(16) NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  user_id RAW(16) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  label VARCHAR2(120) NOT NULL,
  token_hash VARCHAR2(255) NOT NULL,
  last_used_at TIMESTAMP WITH TIME ZONE,
  revoked_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT SYSTIMESTAMP
);

CREATE TABLE audit_events (
  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id RAW(16) NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  actor_id RAW(16) REFERENCES users(id) ON DELETE SET NULL,
  action VARCHAR2(64) NOT NULL,
  target_type VARCHAR2(64),
  target_id RAW(16),
  payload CLOB CHECK (PAYLOAD IS JSON) NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT SYSTIMESTAMP
);

CREATE INDEX idx_users_tenant ON users (tenant_id);
CREATE INDEX idx_projects_tenant_workspace ON projects (tenant_id, workspace_id);
CREATE INDEX idx_audit_events_tenant_created ON audit_events (tenant_id, created_at DESC);

-- Tenant isolation via row-level security. Application sets
--   SET app.current_tenant = '<uuid>';
-- before each statement.
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON projects
    USING (tenant_id::text = current_setting('app.current_tenant', true));

ALTER TABLE workspaces ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON workspaces
    USING (tenant_id::text = current_setting('app.current_tenant', true));

ALTER TABLE audit_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON audit_events
    USING (tenant_id::text = current_setting('app.current_tenant', true));