-- Analytics warehouse — representative Postgres schema.
-- Pattern: classic Kimball star schema with a partitioned fact table
-- and conformed dimensions. This is the shape that maps directly onto
-- Oracle Exadata / Autonomous Data Warehouse conversations.
--
-- Run:
--   pg2oracle examples/warehouse/postgres.sql -o examples/warehouse/oracle.sql --report examples/warehouse/compat.md

CREATE TABLE dim_customer (
  customer_key NUMBER(19) PRIMARY KEY,
  customer_id VARCHAR2(64) NOT NULL UNIQUE,
  name VARCHAR2(200) NOT NULL,
  segment VARCHAR2(64),
  country_code CHAR(2),
  region VARCHAR2(64),
  industry VARCHAR2(120),
  annual_revenue_band VARCHAR2(32),
  effective_from DATE NOT NULL,
  effective_to DATE,
  is_current NUMBER(1) NOT NULL DEFAULT 1
);

CREATE TABLE dim_product (
  product_key NUMBER(19) PRIMARY KEY,
  sku VARCHAR2(64) NOT NULL UNIQUE,
  name VARCHAR2(200) NOT NULL,
  category VARCHAR2(120),
  subcategory VARCHAR2(120),
  brand VARCHAR2(120),
  list_price NUMBER(12,2),
  cost NUMBER(12,2),
  is_active NUMBER(1) NOT NULL DEFAULT 1
);

CREATE TABLE dim_date (
  date_key NUMBER(10) PRIMARY KEY,
  full_date DATE NOT NULL UNIQUE,
  day_of_month NUMBER(5) NOT NULL,
  day_of_week NUMBER(5) NOT NULL,
  week_of_year NUMBER(5) NOT NULL,
  month NUMBER(5) NOT NULL,
  month_name VARCHAR2(20) NOT NULL,
  quarter NUMBER(5) NOT NULL,
  year NUMBER(5) NOT NULL,
  is_weekend NUMBER(1) NOT NULL,
  is_holiday NUMBER(1) NOT NULL DEFAULT 0
);

CREATE TABLE dim_store (
  store_key NUMBER(19) PRIMARY KEY,
  store_id VARCHAR2(32) NOT NULL UNIQUE,
  name VARCHAR2(200) NOT NULL,
  channel VARCHAR2(32) NOT NULL,
  country_code CHAR(2),
  region VARCHAR2(64),
  opened_date DATE
);

-- Fact table — partitioned by month. Order-of-magnitude this is the
-- table that drives Exadata / ADW sizing in M&A diligence.
CREATE TABLE fact_sales (
  sale_id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
  date_key NUMBER(10) NOT NULL REFERENCES dim_date(date_key),
  customer_key NUMBER(19) NOT NULL REFERENCES dim_customer(customer_key),
  product_key NUMBER(19) NOT NULL REFERENCES dim_product(product_key),
  store_key NUMBER(19) NOT NULL REFERENCES dim_store(store_key),
  order_id VARCHAR2(64) NOT NULL,
  quantity NUMBER(10) NOT NULL,
  unit_price NUMBER(12,2) NOT NULL,
  discount_amount NUMBER(12,2) NOT NULL DEFAULT 0,
  tax_amount NUMBER(12,2) NOT NULL DEFAULT 0,
  net_amount NUMBER(14,2) NOT NULL,
  currency_code CHAR(3) NOT NULL DEFAULT 'USD',
  sale_ts TIMESTAMP WITH TIME ZONE NOT NULL,
  raw_payload CLOB CHECK (RAW_PAYLOAD IS JSON),
  PRIMARY KEY (sale_id, sale_ts)
);

CREATE TABLE fact_sales_2025_q1 PARTITION OF fact_sales
    FOR VALUES FROM ('2025-01-01') TO ('2025-04-01');
CREATE TABLE fact_sales_2025_q2 PARTITION OF fact_sales
    FOR VALUES FROM ('2025-04-01') TO ('2025-07-01');

CREATE INDEX idx_fact_sales_customer ON fact_sales (customer_key);
CREATE INDEX idx_fact_sales_product ON fact_sales (product_key);
CREATE INDEX idx_fact_sales_date ON fact_sales (date_key);

-- Aggregate materialized view for dashboard queries.
CREATE MATERIALIZED VIEW mv_daily_sales_by_region AS
SELECT
    d.full_date,
    c.region,
    p.category,
    SUM(f.net_amount) AS total_revenue,
    SUM(f.quantity) AS total_units,
    COUNT(DISTINCT f.customer_key) AS unique_customers
FROM fact_sales f
JOIN dim_date d ON d.date_key = f.date_key
JOIN dim_customer c ON c.customer_key = f.customer_key
JOIN dim_product p ON p.product_key = f.product_key
GROUP BY d.full_date, c.region, p.category;