#!/usr/bin/env bash
# pg2ora UAT — 12 acceptance criteria.
# Runs against the built binary (dist/cli.cjs). Exits 0 if all pass.
set -u
CLI="node dist/cli.cjs"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

pass=0
fail=0
check() {
  local name="$1"; shift
  if "$@" > "$TMP/out" 2> "$TMP/err"; then
    echo "  ✓ $name"
    pass=$((pass + 1))
  else
    echo "  ✗ $name"
    echo "    ---- stdout ----"; sed 's/^/    /' "$TMP/out"
    echo "    ---- stderr ----"; sed 's/^/    /' "$TMP/err"
    fail=$((fail + 1))
  fi
}

assert_contains() {
  local file="$1" needle="$2"
  grep -qF -- "$needle" "$file" || { echo "    expected to find: $needle"; return 1; }
}

assert_not_contains() {
  local file="$1" needle="$2"
  if grep -qF -- "$needle" "$file"; then echo "    should not contain: $needle"; return 1; fi
}

echo "pg2ora UAT — 12 criteria"
echo "------------------------"

# 1. --help works without input
check "1. --help prints usage" bash -c "$CLI --help | grep -q 'Translate PostgreSQL DDL'"

# 2. --version prints semver
check "2. --version prints 0.1.0" bash -c "$CLI --version | grep -q '0.1.0'"

# 3. simple file translation: serial → IDENTITY, text → CLOB
cat > "$TMP/simple.sql" <<'SQL'
CREATE TABLE users (id serial, email text);
SQL
check "3. file in → file out (serial+text)" bash -c "
  $CLI '$TMP/simple.sql' -o '$TMP/simple.ora.sql' &&
  grep -q 'GENERATED BY DEFAULT AS IDENTITY' '$TMP/simple.ora.sql' &&
  grep -q 'CLOB' '$TMP/simple.ora.sql'
"

# 4. stdin → stdout pipe
check "4. stdin → stdout pipe" bash -c "
  echo 'CREATE TABLE t (id serial);' | $CLI > '$TMP/pipe.sql' &&
  grep -q 'GENERATED BY DEFAULT AS IDENTITY' '$TMP/pipe.sql'
"

# 5. CRLF normalization (Windows line endings)
printf 'CREATE TABLE t (id serial);\r\nCREATE TABLE u (id int);\r\n' > "$TMP/crlf.sql"
check "5. CRLF input translates identically" bash -c "
  $CLI '$TMP/crlf.sql' -o '$TMP/crlf.ora.sql' &&
  grep -q 'GENERATED BY DEFAULT AS IDENTITY' '$TMP/crlf.ora.sql' &&
  grep -q 'NUMBER(10)' '$TMP/crlf.ora.sql'
"

# 6. boolean DEFAULT true → DEFAULT 1
cat > "$TMP/bool.sql" <<'SQL'
CREATE TABLE t (active boolean DEFAULT true, deleted boolean DEFAULT false);
SQL
check "6. boolean defaults rewritten" bash -c "
  $CLI '$TMP/bool.sql' -o '$TMP/bool.ora.sql' &&
  grep -q 'DEFAULT 1' '$TMP/bool.ora.sql' &&
  grep -q 'DEFAULT 0' '$TMP/bool.ora.sql'
"

# 7. gen_random_uuid() default dropped + warning emitted
cat > "$TMP/uuid.sql" <<'SQL'
CREATE TABLE t (id uuid DEFAULT gen_random_uuid());
SQL
check "7. gen_random_uuid() dropped + report flags it" bash -c "
  $CLI '$TMP/uuid.sql' -o '$TMP/uuid.ora.sql' --report '$TMP/uuid.md' &&
  ! grep -q 'gen_random_uuid' '$TMP/uuid.ora.sql' &&
  grep -q 'default expression dropped' '$TMP/uuid.md'
"

# 8. long identifier (>30 chars) warned but NOT renamed
LONG="this_is_a_very_long_identifier_over_30"
cat > "$TMP/long.sql" <<SQL
CREATE TABLE $LONG (id serial);
SQL
check "8. long identifier preserved + warned" bash -c "
  $CLI '$TMP/long.sql' -o '$TMP/long.ora.sql' --report '$TMP/long.md' &&
  grep -q '$LONG' '$TMP/long.ora.sql' &&
  grep -q 'long identifier' '$TMP/long.md'
"

# 9. leading comment regression — first table not skipped
cat > "$TMP/leadcomment.sql" <<'SQL'
-- header comment
CREATE TABLE users (id serial, email text);
SQL
check "9. leading comment does not skip first table" bash -c "
  $CLI '$TMP/leadcomment.sql' -o '$TMP/leadcomment.ora.sql' &&
  grep -q 'GENERATED BY DEFAULT AS IDENTITY' '$TMP/leadcomment.ora.sql' &&
  grep -q -- '-- header comment' '$TMP/leadcomment.ora.sql'
"

# 10. --strict exits 2 when warnings present
check "10. --strict exit code 2 on warnings" bash -c "
  $CLI '$TMP/uuid.sql' -o '$TMP/strict.sql' --strict
  test \$? -eq 2
"

# 11. --strict exits 0 when clean
cat > "$TMP/clean.sql" <<'SQL'
CREATE TABLE t (id integer, name varchar(255));
SQL
check "11. --strict exit code 0 when clean" bash -c "
  $CLI '$TMP/clean.sql' -o '$TMP/clean.ora.sql' --strict
"

# 12. Ghost CMS example translates and produces a non-empty report
check "12. Ghost CMS example translates with report" bash -c "
  $CLI examples/ghost/postgres.sql -o '$TMP/ghost.ora.sql' --report '$TMP/ghost.md' &&
  test \$(wc -l < '$TMP/ghost.ora.sql') -gt 50 &&
  grep -q 'compatibility report' '$TMP/ghost.md'
"

# 13. array type warned + passed through (not silently corrupted to "CLOB []")
cat > "$TMP/array.sql" <<'SQL'
CREATE TABLE posts (id serial, tags text[]);
SQL
check "13. array type warned, not silently corrupted" bash -c "
  $CLI '$TMP/array.sql' -o '$TMP/array.ora.sql' --report '$TMP/array.md' &&
  ! grep -qE 'CLOB\s*\[' '$TMP/array.ora.sql' &&
  grep -q 'array type' '$TMP/array.md'
"

# 14. quoted hyphenated jsonb column produces quoted CHECK identifier
cat > "$TMP/jq.sql" <<'SQL'
CREATE TABLE t ("user-data" jsonb);
SQL
check "14. quoted jsonb column → quoted IS JSON ref" bash -c "
  $CLI '$TMP/jq.sql' -o '$TMP/jq.ora.sql' &&
  grep -qF '\"user-data\" IS JSON' '$TMP/jq.ora.sql'
"

# 15. CREATE TABLE trailing clause (PARTITION BY/INHERITS/TABLESPACE) flagged + dropped
cat > "$TMP/tail.sql" <<'SQL'
CREATE TABLE t (id serial) PARTITION BY RANGE (id);
SQL
check "15. trailing PARTITION BY flagged" bash -c "
  $CLI '$TMP/tail.sql' -o '$TMP/tail.ora.sql' --report '$TMP/tail.md' &&
  ! grep -q 'PARTITION BY' '$TMP/tail.ora.sql' &&
  grep -q 'table option dropped' '$TMP/tail.md'
"

# 16. comment containing comma in column body does not break the splitter
cat > "$TMP/cmt.sql" <<'SQL'
CREATE TABLE t (a int /* note: a,b,c */, b int);
SQL
check "16. comma inside /* comment */ does not split column list" bash -c "
  $CLI '$TMP/cmt.sql' -o '$TMP/cmt.ora.sql' &&
  grep -q 'a NUMBER(10)' '$TMP/cmt.ora.sql' &&
  grep -q 'b NUMBER(10)' '$TMP/cmt.ora.sql'
"

# 17. ALTER TABLE SET DATA TYPE: passed through verbatim with high-severity warning
cat > "$TMP/alter.sql" <<'SQL'
ALTER TABLE t ALTER COLUMN c SET DATA TYPE varchar(20);
SQL
check "17. ALTER TABLE SET DATA TYPE flagged, not naive-rewritten" bash -c "
  $CLI '$TMP/alter.sql' -o '$TMP/alter.ora.sql' --report '$TMP/alter.md' &&
  grep -q 'SET DATA TYPE' '$TMP/alter.ora.sql' &&
  grep -q 'ALTER TABLE not translated' '$TMP/alter.md'
"

# 18. CREATE INDEX INCLUDE (...) flagged + stripped
cat > "$TMP/idx.sql" <<'SQL'
CREATE INDEX i ON t (a) INCLUDE (b);
SQL
check "18. CREATE INDEX INCLUDE flagged + stripped" bash -c "
  $CLI '$TMP/idx.sql' -o '$TMP/idx.ora.sql' --report '$TMP/idx.md' &&
  ! grep -q 'INCLUDE' '$TMP/idx.ora.sql' &&
  grep -q 'index feature dropped' '$TMP/idx.md'
"

# 19. EXCLUDE constraint flagged
cat > "$TMP/excl.sql" <<'SQL'
CREATE TABLE rooms (id serial, room int, period int4range, EXCLUDE USING gist (room WITH =, period WITH &&));
SQL
check "19. EXCLUDE constraint flagged high" bash -c "
  $CLI '$TMP/excl.sql' -o '$TMP/excl.ora.sql' --report '$TMP/excl.md' &&
  grep -q 'EXCLUDE constraint' '$TMP/excl.md'
"

# 20. varchar(>4000) flagged
cat > "$TMP/big.sql" <<'SQL'
CREATE TABLE t (s varchar(5000));
SQL
check "20. varchar(>4000) flagged out-of-range" bash -c "
  $CLI '$TMP/big.sql' -o '$TMP/big.ora.sql' --report '$TMP/big.md' &&
  grep -q 'length out of range' '$TMP/big.md'
"

# 21. numeric(>38) flagged
cat > "$TMP/np.sql" <<'SQL'
CREATE TABLE t (n numeric(100,2));
SQL
check "21. numeric(>38) flagged out-of-range" bash -c "
  $CLI '$TMP/np.sql' -o '$TMP/np.ora.sql' --report '$TMP/np.md' &&
  grep -q 'precision out of range' '$TMP/np.md'
"

echo "------------------------"
echo "Passed: $pass / $((pass + fail))"
test $fail -eq 0
