/**
 * Type mapping table: PostgreSQL → Oracle.
 *
 * Hardcoded on purpose. No JSON file lookup, no path resolution.
 * If you want to change a mapping, edit this file and ship a new version.
 *
 * Each entry has:
 *   - pg: the lowercased postgres type name (or canonical form)
 *   - oracle: the oracle type expression
 *   - warn: optional warning surfaced in the compatibility report
 *   - severity: "info" | "warn" | "high" — drives --strict exit code
 */
export type Severity = "info" | "warn" | "high";

export interface TypeMapping {
  pg: string;
  oracle: string;
  warn?: string;
  severity?: Severity;
}

export const TYPE_MAPPINGS: readonly TypeMapping[] = [
  // Integer family
  { pg: "smallint", oracle: "NUMBER(5)" },
  { pg: "int2", oracle: "NUMBER(5)" },
  { pg: "integer", oracle: "NUMBER(10)" },
  { pg: "int", oracle: "NUMBER(10)" },
  { pg: "int4", oracle: "NUMBER(10)" },
  { pg: "bigint", oracle: "NUMBER(19)" },
  { pg: "int8", oracle: "NUMBER(19)" },

  // Auto-increment
  { pg: "serial", oracle: "NUMBER(10) GENERATED BY DEFAULT AS IDENTITY" },
  { pg: "bigserial", oracle: "NUMBER(19) GENERATED BY DEFAULT AS IDENTITY" },

  // Floating / decimal
  { pg: "real", oracle: "BINARY_FLOAT" },
  { pg: "float4", oracle: "BINARY_FLOAT" },
  { pg: "double precision", oracle: "BINARY_DOUBLE" },
  { pg: "float8", oracle: "BINARY_DOUBLE" },
  { pg: "numeric", oracle: "NUMBER" },
  { pg: "decimal", oracle: "NUMBER" },

  // Text family
  { pg: "text", oracle: "CLOB" },
  { pg: "varchar", oracle: "VARCHAR2(4000)", warn: "varchar without length: defaulted to VARCHAR2(4000). Oracle stores VARCHAR2 by BYTE or CHAR depending on NLS_LENGTH_SEMANTICS — verify on target.", severity: "high" },
  { pg: "character varying", oracle: "VARCHAR2(4000)", warn: "character varying without length: defaulted to VARCHAR2(4000). Oracle byte/char semantics depend on NLS_LENGTH_SEMANTICS.", severity: "high" },
  { pg: "char", oracle: "CHAR(1)" },
  { pg: "character", oracle: "CHAR(1)" },

  // Boolean
  { pg: "boolean", oracle: "NUMBER(1)", warn: "boolean → NUMBER(1): true/false rewritten as 1/0. CHECK constraints not auto-added.", severity: "warn" },
  { pg: "bool", oracle: "NUMBER(1)", warn: "bool → NUMBER(1): true/false rewritten as 1/0.", severity: "warn" },

  // Time
  { pg: "timestamp", oracle: "TIMESTAMP" },
  { pg: "timestamp without time zone", oracle: "TIMESTAMP" },
  { pg: "timestamptz", oracle: "TIMESTAMP WITH TIME ZONE" },
  { pg: "timestamp with time zone", oracle: "TIMESTAMP WITH TIME ZONE" },
  { pg: "date", oracle: "DATE" },
  { pg: "time", oracle: "TIMESTAMP", warn: "time → TIMESTAMP: Oracle has no TIME-only type; date component will be 1970-01-01 unless rewritten.", severity: "warn" },

  // Binary / UUID
  { pg: "uuid", oracle: "RAW(16)", warn: "uuid → RAW(16): application must convert UUID strings to 16-byte binary on insert.", severity: "warn" },
  { pg: "bytea", oracle: "BLOB" },

  // Structured
  // __COLREF__ is replaced with a syntactically-valid Oracle reference to the
  // column being checked: quoted name verbatim if the source was quoted,
  // otherwise the unquoted Oracle-uppercase identifier (matches what Oracle
  // creates for unquoted column names).
  { pg: "json", oracle: "CLOB CHECK (__COLREF__ IS JSON)", warn: "json → CLOB with IS JSON check. Native Oracle JSON type only available 21c+; this works on 12c+.", severity: "warn" },
  { pg: "jsonb", oracle: "CLOB CHECK (__COLREF__ IS JSON)", warn: "jsonb → CLOB with IS JSON check. jsonb's binary storage and indexing semantics do NOT translate; queries using jsonb operators (@>, ->) must be rewritten.", severity: "high" },
];

/**
 * Look up a Postgres type. Returns null if no mapping exists.
 * Matching is case-insensitive and ignores parameter parens (e.g. "varchar(255)").
 */
export function findMapping(pgType: string): TypeMapping | null {
  const normalized = pgType.trim().toLowerCase();
  // Exact match first
  const exact = TYPE_MAPPINGS.find((m) => m.pg === normalized);
  if (exact) return exact;
  // Try without parameters: "varchar(255)" → "varchar"
  const base = normalized.replace(/\s*\([^)]*\)\s*$/, "").trim();
  return TYPE_MAPPINGS.find((m) => m.pg === base) ?? null;
}

/**
 * Map a Postgres type expression (possibly with length, e.g. "varchar(255)")
 * to an Oracle type expression. Preserves parameters where Oracle accepts them.
 *
 * Returns { oracle, warn?, severity? } or null if no mapping found.
 */
export interface MapResult {
  oracle: string;
  warn?: string;
  severity?: Severity;
}

export function mapType(pgType: string, colNameRaw?: string): MapResult | null {
  const trimmed = pgType.trim();
  const m = findMapping(trimmed);
  if (!m) return null;

  // Length-preserving rules
  const parenMatch = trimmed.match(/\(([^)]+)\)\s*$/);
  const baseLower = trimmed.replace(/\s*\([^)]*\)\s*$/, "").trim().toLowerCase();

  let oracle = m.oracle;
  let warn = m.warn;
  let severity = m.severity;

  if (parenMatch) {
    const params = parenMatch[1]!.trim();
    if (baseLower === "varchar" || baseLower === "character varying") {
      oracle = `VARCHAR2(${params})`;
      // Length supplied → the "defaulted to VARCHAR2(4000)" warning no longer applies.
      warn = undefined;
      severity = undefined;
    } else if (baseLower === "char" || baseLower === "character") {
      oracle = `CHAR(${params})`;
    } else if (baseLower === "numeric" || baseLower === "decimal") {
      oracle = `NUMBER(${params})`;
    } else if (baseLower === "timestamp" || baseLower === "timestamp without time zone") {
      oracle = `TIMESTAMP(${params})`;
    } else if (baseLower === "timestamptz" || baseLower === "timestamp with time zone") {
      oracle = `TIMESTAMP(${params}) WITH TIME ZONE`;
    }
  }

  // Substitute __COLREF__ placeholder for IS JSON checks.
  // colNameRaw may be quoted ("foo") or bare (foo) — preserve the form so
  // Oracle resolves the same identifier the column is created with.
  if (colNameRaw && oracle.includes("__COLREF__")) {
    const ref = /^"[^"]+"$/.test(colNameRaw)
      ? colNameRaw // already quoted, case-sensitive identifier
      : colNameRaw.toUpperCase(); // bare → Oracle uppercases at create time
    oracle = oracle.replace(/__COLREF__/g, ref);
  }

  return { oracle, warn, severity };
}
